version: 2.1
jobs:
  build: 
    docker:
      - image: 17-jdk-alpine3.14
    steps:
      - checkout
      - run:
          name: "Build"
          command: "./gradlew build"
workflows:
  build-workflow:
    jobs:
      - build
